=== Jorgepastorr/apuntes/docs/bases_datos/mongo/json_dades_exemple/edx/bios.schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Schema title",
  "description": "Schema description",
  "type": "object",
  "properties": {
    "_id": {
      "type": "number"
    },
    "name": {
      "type": "object",
      "properties": {
        "first": {
          "type": "string"
        },
        "last": {
          "type": "string"
        }
      }
    },
    "birthYear": {
      "type": "number"
    },
    "deathYear": {
      "type": "number"
    },
    "contribs": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "awards": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "award": {
              "type": "string"
            },
            "year": {
              "type": "number"
            },
            "by": {
              "type": "string"
            }
          }
        },
        {
          "type": "object",
          "properties": {
            "award": {
              "type": "string"
            },
            "year": {
              "type": "number"
            },
            "by": {
              "type": "string"
            }
          }
        },
        {
          "type": "object",
          "properties": {
            "award": {
              "type": "string"
            },
            "year": {
              "type": "number"
            },
            "by": {
              "type": "string"
            }
          }
        },
        {
          "type": "object",
          "properties": {
            "award": {
              "type": "string"
            },
            "year": {
              "type": "number"
            },
            "by": {
              "type": "string"
            }
          }
        }
      ]
    }
  }
}

=== Jorgepastorr/apuntes/docs/bases_datos/mongo/json_dades_exemple/edx/bios-sample.json
{
  "_id": 1,
  "name": {
    "first": "John",
    "last": "Backus"
  },
  "birthYear": 1924,
  "deathYear": 2007,
  "contribs": [
    "Fortran",
    "ALGOL",
    "Backus-Naur Form",
    "FP"
  ],
  "awards": [
    {
      "award": "W.W. McDowell Award",
      "year": 1967,
      "by": "IEEE Computer Society"
    },
    {
      "award": "National Medal of Science",
      "year": 1975,
      "by": "National Science Foundation"
    },
    {
      "award": "Turing Award",
      "year": 1977,
      "by": "ACM"
    },
    {
      "award": "Draper Prize",
      "year": 1993,
      "by": "National Academy of Engineering"
    }
  ]
}
