=== Jorgepastorr/apuntes/docs/bases_datos/mongo/json_dades_exemple/edx/books.schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Schema title",
  "description": "Schema description",
  "type": "object",
  "properties": {
    "_id": {
      "type": "object",
      "properties": {
        "$oid": {
          "type": "string"
        }
      }
    },
    "author": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "isbn": {
      "type": "string"
    },
    "price": {
      "type": "object",
      "properties": {
        "currency": {
          "type": "string"
        },
        "discount": {
          "type": "number"
        },
        "msrp": {
          "type": "number"
        }
      }
    },
    "publicationYear": {
      "type": "number"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "title": {
      "type": "string"
    }
  }
}

=== Jorgepastorr/apuntes/docs/bases_datos/mongo/json_dades_exemple/edx/books-sample.json
{
  "_id": {
    "$oid": "4d2a6084c6237b412fcd5597"
  },
  "author": [
    "Brian P. Hogan"
  ],
  "isbn": "978-1-93435-668-5",
  "price": {
    "currency": "USD",
    "discount": 21.78,
    "msrp": 33
  },
  "publicationYear": 2010,
  "tags": [
    "html5",
    "cascading style sheets",
    "css",
    "html",
    "pragmatic programmer",
    "silverlight",
    "web development",
    "web standards",
    "css3",
    "foo"
  ],
  "title": "HTML5 and CSS3"
}
