=== Jorgepastorr/apuntes/docs/bases_datos/mongo/json_dades_exemple/digg/stories.schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Schema title",
  "description": "Schema description",
  "type": "object",
  "properties": {
    "_id": {
      "type": "object",
      "properties": {
        "$oid": {
          "type": "string"
        }
      }
    },
    "href": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "comments": {
      "type": "number"
    },
    "container": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "short_name": {
          "type": "string"
        }
      }
    },
    "submit_date": {
      "type": "number"
    },
    "topic": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "short_name": {
          "type": "string"
        }
      }
    },
    "promote_date": {
      "type": "number"
    },
    "id": {
      "type": "string"
    },
    "media": {
      "type": "string"
    },
    "diggs": {
      "type": "number"
    },
    "description": {
      "type": "string"
    },
    "link": {
      "type": "string"
    },
    "user": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "registered": {
          "type": "number"
        },
        "fullname": {
          "type": "string"
        },
        "icon": {
          "type": "string"
        },
        "profileviews": {
          "type": "number"
        }
      }
    },
    "status": {
      "type": "string"
    },
    "shorturl": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "short_url": {
            "type": "string"
          },
          "view_count": {
            "type": "number"
          }
        }
      }
    }
  }
}

=== Jorgepastorr/apuntes/docs/bases_datos/mongo/json_dades_exemple/digg/stories-sample.json
{
  "_id": {
    "$oid": "4ba267dc238d3ba3ca000001"
  },
  "href": "http://digg.com/people/Jedi_believer_who_refused_to_remove_hood_gets_an_apology",
  "title": "'Jedi' believer who refused to remove hood gets an apology!",
  "comments": 153,
  "container": {
    "name": "Offbeat",
    "short_name": "offbeat"
  },
  "submit_date": 1268771801,
  "topic": {
    "name": "People",
    "short_name": "people"
  },
  "promote_date": 1268915964,
  "id": "19970068",
  "media": "news",
  "diggs": 404,
  "description": "Chris Jarvis is a member of the International Church of Jediism - based on the famous Star Wars films - whose doctrine states followers can wear hoods.",
  "link": "http://www.dailymail.co.uk/news/article-1258365/Jedi-believer-wins-apology-Jobcentre-kicked-wearing-hood.html",
  "user": {
    "name": "babychen",
    "registered": 1141570067,
    "fullname": "Babychen Mathew",
    "icon": "http://digg.com/users/babychen/l.png",
    "profileviews": 24749
  },
  "status": "popular",
  "shorturl": [
    {
      "short_url": "http://digg.com/d31Ln7s",
      "view_count": 3682
    }
  ]
}
