=== Jorgepastorr/apuntes/docs/bases_datos/mongo/json_dades_exemple/imdb/movies.schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Schema title",
  "description": "Schema description",
  "type": "object",
  "properties": {
    "_id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "year": {
      "type": "number"
    },
    "rating": {
      "type": "string"
    },
    "runtime": {
      "type": "number"
    },
    "genre": {
      "type": "string"
    },
    "earnings_rank": {
      "type": "number"
    },
    "actors": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          }
        },
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          }
        },
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          }
        },
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          }
        },
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          }
        }
      ]
    },
    "directors": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== Jorgepastorr/apuntes/docs/bases_datos/mongo/json_dades_exemple/imdb/movies-sample.json
{
  "_id": "0499549",
  "name": "Avatar",
  "year": 2009,
  "rating": "PG-13",
  "runtime": 162,
  "genre": "AVYS",
  "earnings_rank": 1,
  "actors": [
    {
      "id": "0941777",
      "name": "Sam Worthington"
    },
    {
      "id": "0757855",
      "name": "Zoe Saldana"
    },
    {
      "id": "0000244",
      "name": "Sigourney Weaver"
    },
    {
      "id": "0002332",
      "name": "Stephen Lang"
    },
    {
      "id": "0735442",
      "name": "Michelle Rodriguez"
    }
  ],
  "directors": [
    {
      "id": "0000116",
      "name": "James Cameron"
    }
  ]
}
