=== Jorgepastorr/apuntes/docs/bases_datos/mongo/json_dades_exemple/twitter/tweets.schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Schema title",
  "description": "Schema description",
  "type": "object",
  "properties": {
    "text": {
      "type": "string"
    },
    "in_reply_to_status_id": {
      "type": "null"
    },
    "retweet_count": {
      "type": "null"
    },
    "contributors": {
      "type": "null"
    },
    "created_at": {
      "type": "string"
    },
    "geo": {
      "type": "null"
    },
    "source": {
      "type": "string"
    },
    "coordinates": {
      "type": "null"
    },
    "in_reply_to_screen_name": {
      "type": "null"
    },
    "truncated": {
      "type": "boolean"
    },
    "entities": {
      "type": "object",
      "properties": {
        "user_mentions": {
          "type": "array"
        },
        "urls": {
          "type": "array"
        },
        "hashtags": {
          "type": "array"
        }
      }
    },
    "retweeted": {
      "type": "boolean"
    },
    "place": {
      "type": "null"
    },
    "user": {
      "type": "object",
      "properties": {
        "friends_count": {
          "type": "number"
        },
        "profile_sidebar_fill_color": {
          "type": "string"
        },
        "location": {
          "type": "string"
        },
        "verified": {
          "type": "boolean"
        },
        "follow_request_sent": {
          "type": "null"
        },
        "favourites_count": {
          "type": "number"
        },
        "profile_sidebar_border_color": {
          "type": "string"
        },
        "profile_image_url": {
          "type": "string"
        },
        "geo_enabled": {
          "type": "boolean"
        },
        "created_at": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "time_zone": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "screen_name": {
          "type": "string"
        },
        "notifications": {
          "type": "null"
        },
        "profile_background_color": {
          "type": "string"
        },
        "listed_count": {
          "type": "number"
        },
        "lang": {
          "type": "string"
        },
        "profile_background_image_url": {
          "type": "string"
        },
        "statuses_count": {
          "type": "number"
        },
        "following": {
          "type": "null"
        },
        "profile_text_color": {
          "type": "string"
        },
        "protected": {
          "type": "boolean"
        },
        "show_all_inline_media": {
          "type": "boolean"
        },
        "profile_background_tile": {
          "type": "boolean"
        },
        "name": {
          "type": "string"
        },
        "contributors_enabled": {
          "type": "boolean"
        },
        "profile_link_color": {
          "type": "string"
        },
        "followers_count": {
          "type": "number"
        },
        "id": {
          "type": "number"
        },
        "profile_use_background_image": {
          "type": "boolean"
        },
        "utc_offset": {
          "type": "number"
        }
      }
    },
    "favorited": {
      "type": "boolean"
    },
    "in_reply_to_user_id": {
      "type": "null"
    },
    "id": {
      "type": "number"
    }
  }
}

=== Jorgepastorr/apuntes/docs/bases_datos/mongo/json_dades_exemple/twitter/tweets-sample.json
{
  "text": "eu preciso de terminar de fazer a minha tabela, está muito foda **",
  "in_reply_to_status_id": null,
  "retweet_count": null,
  "contributors": null,
  "created_at": "Thu Sep 02 18:11:23 +0000 2010",
  "geo": null,
  "source": "web",
  "coordinates": null,
  "in_reply_to_screen_name": null,
  "truncated": false,
  "entities": {
    "user_mentions": [],
    "urls": [],
    "hashtags": []
  },
  "retweeted": false,
  "place": null,
  "user": {
    "friends_count": 73,
    "profile_sidebar_fill_color": "768575",
    "location": "",
    "verified": false,
    "follow_request_sent": null,
    "favourites_count": 1,
    "profile_sidebar_border_color": "1c9dbd",
    "profile_image_url": "http://a2.twimg.com/profile_images/1036412454/OgAAADXK9q6kaxrvfwQTINH66RVLAH9YHb-veRTA4FaWb9KtbGGV_yKTGzmvzTfJidqAb5gK_mpspIE-MIvAASGH2CwAm1T1UIPQk0-HS8x_TV5kdnW30nch7ODk-1_normal.jpg",
    "geo_enabled": false,
    "created_at": "Fri Jul 03 21:44:05 +0000 2009",
    "description": "só os loucos sabem (:",
    "time_zone": "Brasilia",
    "url": "http://http://www.orkut.com.br/Main#Profile?uid=1433295880233078770",
    "screen_name": "Bia_cunha1",
    "notifications": null,
    "profile_background_color": "081114",
    "listed_count": 0,
    "lang": "en",
    "profile_background_image_url": "http://a1.twimg.com/profile_background_images/133178546/biatwitter.jpg",
    "statuses_count": 3504,
    "following": null,
    "profile_text_color": "25b8c2",
    "protected": false,
    "show_all_inline_media": false,
    "profile_background_tile": true,
    "name": "Beatriz Helena Cunha",
    "contributors_enabled": false,
    "profile_link_color": "eb55b6",
    "followers_count": 102,
    "id": 53507833,
    "profile_use_background_image": true,
    "utc_offset": -10800
  },
  "favorited": false,
  "in_reply_to_user_id": null,
  "id": 22819396900
}
